---
title: "General Data for COVID-19"
output: flexdashboard::flex_dashboard
runtime: shiny
  
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(DT)

# include the functions from the file
source("MyFunctionsForROUData.R")

# read the Romanian shape file
RomShape <- readRomShape()

# Read the Romanian Covid data from the imput file
CovidData <- reactive({
  #if (is.null(input$CovidFile$datapath)) return()
  readRouData(input$CovidFile$datapath)
  })

# merge the Covid Data with the map data
CovidShape <- reactive({
  new_group_Map_Covid(CovidData(),RomShape)
})
```


Input{.sidebar}
=====================

```{r}
fileInput("CovidFile", "Choose COVID-19 data file",
          multiple = FALSE)

#actionButton("Load", "Load data")

#actionButton("do", "Plot"),
#fileInput("ShapeFile", "Choose COVID-19 data file",
#          multiple = FALSE,
#          accept = c("text/csv",
#                     "text/comma-separated-values,text/plain",
#                     ".csv"))
#           # actionButton("do", "Plot"),
sliderInput("date", "Date:",
            min = date("2020-10-28"), max = date("2021-09-01"),
            value = date("2021-09-01"), animate = TRUE)

observeEvent(input$CovidFile,{
  updateSliderInput(session, "date",
                    min = date("2020-10-28"),
                    max = max(CovidData()$parsed_date),
                    value = max(CovidData()$parsed_date))
})

#renderPlotly({
# plotTimeData(CovidData())
#}) 
```



COVID-19 Romania
======================

### Temporal trend

```{r}
# plot the Covid data in time
renderPlotly({
  if (is.null(CovidData())) return()
  plotTimeData(CovidData())
}) 
```

### Data

```{r}
# display the data for Covid in time
renderDT({
  if (is.null(CovidData())) return()
  datatable(
    CovidData() %>% select(-incidence, -countyInfectionsNumbers,-large_cities_incidence,-small_cities_incidence) %>% arrange(parsed_date),
    extensions = 'Buttons', 
    options = list(
      scrollX = TRUE,
      scrollY = TRUE,
      dom = 'Blfrtip',
      buttons = c('copy','csv','excel','pdf','print'),
      lengthMenu = list(c(10,25,50,-1), c(10,25,50, "All"))
    ))
})
```


Map
====================

```{r}
# plot the Covid data on the map for the input date
renderPlotly({
  #plotCovidShape(combineRomDataDate(input$date[1], RomShape, CovidData()))
  plot_new_Covid_Shape(CovidShape(), input$date[1])
})
```


Map Data
==============================
```{r}
# Table with all the Covid data on the map and in time
renderDT({
  datatable(
    CovidShape() %>% drop_na(),
    extensions = 'Buttons', 
    options = list(
      scrollX = TRUE,
      scrollY = TRUE,
      dom = 'Blfrtip',
      buttons = c('copy','csv','excel','pdf','print'),
      lengthMenu = list(c(10,25,50,-1), c(10,25,50, "All"))
    ))
})
```
